[workspace]

members = [
    "kernel",
    "common",
    "memory",
    "pe",
    "userspace/syscall",
    # build helpers
    "helpers/ld-link-map",
    "helpers/patcher",
]

default-members = ["kernel"]

[profile.dev]
debug = 0 # symbols are manually patched in