import os

Import("env")
env = env.Clone()

args = ""
if env["build"] == "release":
    args = " --release"

if not env["framepointers"]:
    # setting RUSTFLAGS triggers a full rebuild so only do if unset from default
    env["ENV"]["RUSTFLAGS"] = "-Cforce-frame-pointers=no"

kernel_lib = os.path.join(Dir("#kernel").abspath, "target/domeos/{}/libdomeos_kernel.a".format(env["build"]))
kernel_lib = env.Command(kernel_lib, [], "cargo build" + args, chdir="kernel")
env.AlwaysBuild(kernel_lib)

Export("kernel_lib")

# delete target on clean
#Clean(build, "target")
